/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package raphdine.comptes.ihm;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import raphdine.comptes.ihm.tableau.TableauPanel;
import raphdine.comptes.utils.SwingUtils;

/**
 *
 * @author Raphiki
 */
public class WelcomeFrame extends javax.swing.JFrame {

    private static final Logger LOGGER = LogManager.getLogger();

    /**
     * Creates new form Table
     *
     */
    public WelcomeFrame() {
        initComponents();
        initMyComponents();
    }

    private void initMyComponents() {
        final javax.swing.GroupLayout layout = SwingUtils.extractGroupLayout(tableauPanelContainer);
        final TableauPanel tableauPanel = new TableauPanel();
        layout.setHorizontalGroup(layout.createParallelGroup().addComponent(tableauPanel));
        layout.setVerticalGroup(layout.createParallelGroup().addComponent(tableauPanel));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ongletsPanel = new javax.swing.JTabbedPane();
        tableauPanelContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableauPanelContainer.setForeground(new java.awt.Color(255, 0, 153));

        javax.swing.GroupLayout tableauPanelContainerLayout = new javax.swing.GroupLayout(tableauPanelContainer);
        tableauPanelContainer.setLayout(tableauPanelContainerLayout);
        tableauPanelContainerLayout.setHorizontalGroup(
            tableauPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );
        tableauPanelContainerLayout.setVerticalGroup(
            tableauPanelContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        ongletsPanel.addTab("Ecritures", tableauPanelContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ongletsPanel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ongletsPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane ongletsPanel;
    private javax.swing.JPanel tableauPanelContainer;
    // End of variables declaration//GEN-END:variables

}
